# Generated by Django 2.1.7 on 2019-04-05 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laudoAtendimento', models.TextField(max_length=60, verbose_name='Descrição do atendimento:')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=60, verbose_name='Categoria:')),
                ('descricaoCategoria', models.CharField(max_length=60, verbose_name='Descrição da categoria:')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título:')),
                ('Descricao', models.TextField(verbose_name='Título:')),
                ('telefone', models.CharField(max_length=60, verbose_name='Telefone solicitante')),
                ('data', models.DateTimeField(verbose_name='Data chamado')),
                ('status', models.CharField(max_length=60, verbose_name='Status')),
                ('atendimento', models.ManyToManyField(to='app_helpdesk.Atendimento')),
                ('categoria', models.ManyToManyField(to='app_helpdesk.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('departamento', models.CharField(max_length=60, verbose_name='Departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='departamento',
            field=models.ManyToManyField(to='app_helpdesk.Funcionario'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_helpdesk.Funcionario'),
        ),
    ]
